import re
from types import SimpleNamespace

import numpy as np

from yaiv.defaults.config import ureg

def dyn_file(file):
    alat = None
    with open(file, "r") as lines:
        for line in lines:
            if alat is None and len(line.split())==9:
                alat= float(line.split()[3])*ureg('ang/alat')
                print(alat)
            print(line)

    #return q_point, basis_vec, positions, alat, freqs, vectors, masses

def read_dyn_file(file, qe_format=True):
    """Read the .dyn# file generated by QE and outputs:
    q_point(alat), basis(alat), atomic_positions(alat), frequencies(cm-1), displacements(normalized), alat (au), atomic_masses(2m_e).

    qe_format = Bolean for the displacements output format:
        if True:
            [[x_1,y_1,z_1],
            [x_2,y_2,z_2],
            ...]
        if False:
            One dimensional array
    return q_point, basis, positions, alat, freqs, displacements, atom_mass"""

    read_qpoint = True
    read_vec = False
    first_vec = True
    atom_types = []
    freqs = []
    atom_mass = []
    dyn_out = open(file, "r")
    for line_n, line in enumerate(dyn_out):
        if line_n == 2:  # reads atom types and atoms number
            l = line.split()
            num_atoms = int(l[1])
            num_types = int(l[0])
            alat = float(l[3])
        if line_n > 2 and line_n in range(7, 7 + num_types):  # read atom types
            l = line.split()
            atom_types = atom_types + [l[1][1:]]
            atom_mass = atom_mass + [float(l[3])]
        if line_n > 2 and line_n in range(
            7 + num_types, 7 + num_types + num_atoms
        ):  # read positions
            l = line.split()
            l = [float(i) for i in l]
            pos = np.array(l)
            try:
                positions = np.vstack([positions, pos])
            except NameError:
                positions = pos
        if line_n in [4, 5, 6]:  # Read basis
            l = line.split()
            b = np.array([float(l[0]), float(l[1]), float(l[2])])
            try:
                basis_vec = np.vstack([basis_vec, b])
            except NameError:
                basis_vec = b
        if re.search("q =", line) and read_qpoint == True:  # Reads q_point
            l = line.split()
            q_point = np.array([float(l[3]), float(l[4]), float(l[5])])
            read_qpoint = False
        if read_vec == True and num <= num_atoms:  # Reads displacements
            l = line.split()
            X = complex(float(l[1]), float(l[2]))
            Y = complex(float(l[3]), float(l[4]))
            Z = complex(float(l[5]), float(l[6]))
            if num == 1:
                v = np.array([X, Y, Z])
            else:
                v = np.vstack([v, np.array([X, Y, Z])])
            num = num + 1  # counts the number of atoms
            if num > num_atoms:
                read_vec = False
                if first_vec == True:
                    vectors = [v]
                    first_vec = False
                else:
                    vectors = vectors + [v]
        if re.search("freq", line):  # Reads frequencies
            l = line.split()
            f = float(l[7])
            freqs = np.append(freqs, f)
            read_vec = True
            num = 1  # counter so that we read num_atoms vectors for each freq
    atoms = []
    masses = []
    for p in positions:
        atoms = atoms + [atom_types[int(p[1]) - 1]]
        masses = masses + [atom_mass[int(p[1]) - 1]]
    positions = [atoms, positions[:, 2:]]
    vectors = np.array(vectors)
    if qe_format == False:
        dim = 3 * len(positions[0])
        vectors = vectors.reshape(dim, 1, dim)
    return q_point, basis_vec, positions, alat, freqs, vectors, masses
