from types import SimpleNamespace
from math import gcd
import warnings

import numpy as np

from yaiv.defaults.config import ureg
from yaiv import utils as ut
from yaiv import grep
from yaiv import cell
from yaiv.dev import grep as grepx


__all__ = ["Dyn", "CDW"]


def _QEdyn2Realdyn(
    dyn_mat: np.ndarray | ureg.Quantity, masses: np.ndarray | ureg.Quantity
) -> np.ndarray | ureg.Quantity:
    """
    Convert Quantum ESPRESSO dynamical matrix to the real dynamical matrix in physical units.

    In Quantum ESPRESSO, the dynamical matrix is written in units of [energy/h]^2 * [mass].
    To obtain the true dynamical matrix, whose eigenvalues are squared phonon frequencies (ν²) in
    units of [energy/h]^2, one must divide by √(m_i * m_j) for each atomic block.

    Parameters
    ----------
    dyn_mat : np.ndarray | ureg.Quantity
        The 3N×3N dynamical matrix as written by Quantum ESPRESSO.

    masses : np.ndarray | ureg.Quantity
        Array of atomic masses (length N), one per atom. Units should be consistent
        with those implied in `dyn_mat`. In QE, masses are typically given in units of 2 m_e.

    Returns
    -------
    np.ndarray or Quantity
        The real dynamical matrix with proper normalization, whose eigenvalues
        have units of squared frequencies, e.g., [Ry²/h²] or [s⁻²], depending on units.

    Raises
    ------
    ValueError
        If input shapes are inconsistent or mass array is not one-dimensional.
    """
    # Check unit consistency
    ut._check_unit_consistency([dyn_mat, masses], ["Dynamical matrix", "Atomic masses"])

    # Strip units if present
    if isinstance(dyn_mat, ureg.Quantity):
        units = dyn_mat.units / masses.units
        dyn_mat = dyn_mat.magnitude
        masses = masses.magnitude
    else:
        units = 1

    # Sanity checks
    masses = np.asarray(masses)
    dyn_mat = np.asarray(dyn_mat)

    if masses.ndim != 1:
        raise ValueError("Masses must be a 1D array (one mass per atom).")
    if dyn_mat.shape[0] != dyn_mat.shape[1]:
        raise ValueError("Dynamical matrix must be square.")
    if dyn_mat.shape[0] != 3 * len(masses):
        raise ValueError("Dynamical matrix shape is incompatible with number of atoms.")

    # Transform matrix
    N = len(masses)
    dyn = np.copy(dyn_mat)
    for n in range(N):
        for m in range(N):
            i = 3 * n
            j = 3 * m
            factor = np.sqrt(masses[n] * masses[m])
            dyn[i : i + 3, j : j + 3] /= factor

    return dyn * units


class Dyn:
    def __init__(
        self,
        q=None,
        dyn=None,
        masses=None,
        Cell=None,
    ):
        """
        dyn_mat : np.ndarray | ureg.Quantity
            The (3N × 3N) complex-valued dynamical matrix. If `qe_format_in=True`, this is expected to
            be the raw QE format (including √(mᵢ mⱼ) prefactors); otherwise, it should already be the
            physical dynamical matrix in (Ry/h)² units.

        masses : np.ndarray | ureg.Quantity
            Atomic masses in units of used in the dynamical matrix if qe_format_in is True.
        """
        self.q = q
        self.dyn = dyn
        self.Cell = Cell
        self.masses = masses

    @classmethod
    def from_file(
        cls,
        q_cryst: np.ndarray | ureg.Quantity,
        results_ph_path: str,
        qe_format: bool = True,
    ):
        """
        Reads the Quantum ESPRESSO `.dyn*` file corresponding to a given q-point.

        This function locates the `.dyn*` file generated by `ph.x` that corresponds to a
        desired q-point (in reduced crystalline coordinates), extracts the corresponding dynamical
        matrix, and optionally converts it to the real physical dynamical matrix in units
        of 1 / [time]².

        Parameters
        ----------
        q_cryst : np.ndarray | ureg.Quantity
            The q-point of interest, expressed in reduced crystalline coordinates (fractions of reciprocal lattice vectors).
            If not a `Quantity`, it is assumed to be in `_2pi/crystal` units.

        results_ph_path : str
            Path to the directory containing the Quantum ESPRESSO `ph.x` output `.dyn*` files.

        qe_format : bool, optional
            If True (default), returns the raw QE dynamical matrix (includes sqrt(m_i m_j) mass factors).
            If False, converts the dynamical matrix to true physical form in 1 / [time]² units (Ry/h)^2.

        Returns
        -------
        Dyn
            A new Dynamical matrix instance.
        """
        system = grepx.read_dyn_q(q_cryst, results_ph_path, qe_format)
        atoms = cell.Atoms(
            system.elements, system.positions.magnitude, cell=system.lattice.magnitude
        )
        return cls(
            q=system.q,
            dyn=system.dyn,
            Cell=cell.Cell(atoms=atoms),
            masses=system.masses,
        )

    def diagonalize(
        self,
        qe_format_in: bool = True,
        qe_format_out: bool = True,
    ):
        """
        Diagonalize a dynamical matrix and return phonon frequencies, polarization vectors and displacements.

        This function converts the input dynamical matrix to its physical form (if needed),
        diagonalizes it to obtain phonon frequencies (in cm⁻¹), and computes the corresponding
        normalized displacement vectors.

        Parameters
        ----------
        qe_format_in : bool, optional
            Whether `dyn_mat` is in QE format (default: True). If so, it is converted to the real
            physical format for diagonalization.

        qe_format_out : bool, optional
            Whether to return the normalized displacements and polarization vectors in QE format: an array of shape
            (3N, N_atoms, 3). If False, returns a plain (3N × 3N) array of normalized eigenvectors/displacements where
            polarizations[i] corresponds to eigenvalue freqs[i]**2.

        Returns
        -------
        New attributes to the Dyn object:
            - freqs : np.ndarray
                Array of 3N phonon frequencies in cm⁻¹. Real or negative imaginary parts indicate stable or unstable modes.
            - displacements : np.ndarray
                Normalized displacement vectors of the dynamical matrix. Format depends on `qe_format_out`.
            - polarizations : np.ndarray
                Raw polarization vectors (before mass-weighted normalization). Format depends on `qe_format_out`.

        Raises
        ------
        ValueError
            If eigenvalues are not purely real or imaginary (i.e., contain both parts).
        """
        # Check unit consistency
        dyn_mat, masses = self.dyn, self.masses
        ut._check_unit_consistency(
            [dyn_mat, masses], ["Dynamical matrix", "Atomic masses"]
        )

        # Strip units
        if isinstance(dyn_mat, ureg.Quantity):
            if dyn_mat.dimensionality == ureg("kg/s^2").dimensionality:
                dyn_mat = _QEdyn2Realdyn(dyn_mat, masses)
            dyn, units = dyn_mat.magnitude, (1 * np.sqrt(dyn_mat).units).to("c/cm")
            masses = masses.magnitude
        else:
            if qe_format_in:
                dyn_mat = _QEdyn2Realdyn(dyn_mat, masses)
            dyn, units = dyn_mat, 1

        # Diagonalize
        eigvals, pol = np.linalg.eig(dyn)

        # Convert eigenvalues (ω²) to frequencies in cm⁻¹
        freqs = np.zeros_like(eigvals, dtype=float)
        for i, val in enumerate(np.sqrt(eigvals)):
            if np.isclose(np.imag(val), 0, atol=1e-10):
                freqs[i] = np.real(val)
            elif np.isclose(np.real(val), 0, atol=1e-10):
                freqs[i] = -np.abs(np.imag(val))
            else:
                raise ValueError(
                    f"Complex eigenvalue with both real and imaginary part at index {i}: {val}"
                )

        # Normalize polarization vectors to obtain displacements
        dim = len(masses)
        displacements = np.copy(pol)
        for col in range(pol.shape[1]):
            for i in range(dim):
                displacements[3 * i : 3 * i + 3, col] /= np.sqrt(masses[i])
            displacements[:, col] /= np.linalg.norm(displacements[:, col])

        # Sort by increasing frequency
        order = np.argsort(freqs)
        freqs_sorted = freqs[order] * units
        displacements = displacements[:, order].T
        polarizations = pol[:, order].T

        if qe_format_out:
            displacements = displacements.reshape(len(masses) * 3, len(masses), 3)
            polarizations = polarizations.reshape(len(masses) * 3, len(masses), 3)

        self.freqs = freqs_sorted
        self.displacements = displacements
        self.polarizations = polarizations


def _find_supercell(
    q_cryst: np.ndarray | ureg.Quantity | list[np.ndarray] | list[ureg.Quantity],
) -> SimpleNamespace:
    """
    Compute the minimal supercell that is commensurate with a set of q-points in crystal units.

    This function finds the smallest supercell that accommodates the periodicity
    of the input q-points by ensuring that the phase factors `exp(2πi q·R)` close
    after a finite number of lattice translations. It also computes the corresponding
    phase factor grids over the supercell.

    Parameters
    ----------
    q_cryst : np.ndarray | ureg.Quantity | list[np.ndarray | ureg.Quantity]
        A single q-point or list of q-points, given in crystalline units
        (units of 2π/crystal). If provided with units, they must be `"_2pi/crystal"`.

    Returns
    -------
    SimpleNamespace
        A namespace with the following attributes:
        - size : np.ndarray
            A 3-element integer array defining the minimal commensurate supercell.
        - phase_factors : list[np.ndarray]
            List of 3D complex-valued arrays with the phase factors
            `exp(2πi q·R)` evaluated on the supercell grid for each q-point.
            Each has dimnesion equal to the supercell size [phase_factors.shape = size].
        - q : list[ureg.Quantity]
            The q-points, returned as quantities with units `_2pi/crystal`.

    Raises
    ------
    ValueError
        If q-points do not have units of 2π/crystal, or if no commensurate supercell
        is found in a direction within 100 lattice multiples.
    """
    # Normalize input to list of np.ndarray
    if len(np.shape(q_cryst)) == 1:
        q_cryst = [q_cryst]

    # Check units and convert to magnitudes
    ut._check_unit_consistency(q_cryst)
    if isinstance(q_cryst[0], ureg.Quantity):
        for q in q_cryst:
            if q.units != ureg("_2pi/crystal"):
                raise ValueError("Each q-point must have units of 2π/crystal.")
        q_cryst_mag = [q.magnitude for q in q_cryst]
    else:
        q_cryst_mag = q_cryst

    supersize = np.ones(3, dtype=int)

    for q in q_cryst_mag:
        p_super = np.zeros(3, dtype=int)
        for i, n in enumerate(q):
            for cell in range(1, 101):
                if (cell * n) % 1 == 0:
                    p_super[i] = cell
                    break
            else:
                raise ValueError(
                    f"Could not find commensurate cell for q = {q} in direction {i} "
                    "within 100 multiples. Check that q is rational."
                )
        # LCM between existing and partial supercell
        for i in range(3):
            supersize[i] = supersize[i] * p_super[i] // gcd(supersize[i], p_super[i])

    # Compute phase factors over supercell grid
    phase_factors = []
    for q in q_cryst_mag:
        phases_q = np.empty(supersize, dtype=complex)
        for i in range(supersize[0]):
            for j in range(supersize[1]):
                for k in range(supersize[2]):
                    R = np.array([i, j, k])
                    phases_q[i, j, k] = np.exp(2j * np.pi * np.dot(q, R))
        phase_factors.append(phases_q)

    q_cryst_with_units = [np.array(q) * ureg("_2pi/crystal") for q in q_cryst_mag]

    return SimpleNamespace(
        size=supersize,
        phase_factors=phase_factors,
        q=q_cryst_with_units,
    )


# def distort_crystal(q_points, results_ph, order_parameter, modes, amplitude):
class CDW:
    def __init__(self, dyn_matrices: list):
        self.dyn_matrices = dyn_matrices
        # 1. Read crystal structure
        self.Cell = self.dyn_matrices[0].Cell
        q_cryst = []
        # 2. Get dynamical matrices
        for i in range(len(self.dyn_matrices)):
            self.dyn_matrices[i].diagonalize()
            q_cryst = q_cryst + [self.dyn_matrices[i].q.magnitude]
        self.q = q_cryst
        # 3. Find conmmensurate supercell and get phase factors
        self._supercell = _find_supercell(q_cryst)
        # 4. Build supercell
        self.SuperCell = self.Cell.get_supercell(self._supercell.size)

    @classmethod
    def from_file(cls, q_cryst, results_ph_path):
        if len(np.shape(q_cryst)) == 1:
            q_cryst = [q_cryst]
        dyn_matrices = []
        for q in q_cryst:
            dyn_matrices = dyn_matrices + [Dyn.from_file(q, results_ph_path)]
        return cls(dyn_matrices)

    def distort_crystal(order_paramete=None, modes=None, amplitude=0.01):
        print("TODO")
        # 7. Make Supercell displacement vectors combining phase factors and displacement vectors
        # 8. Add the displacements to create a supercell final displacement
        # 9. Apply displacement
        # 10. Return final cell
        pass
