"""
YAIV | yaiv.phonon
=======================

This module provides tools to handle vibrational properties of crystals from
first-principles calculations.

It includes data structures and utilities to:
- Read `.dyn*` files generated by `ph.x`
- Construct and transform dynamical matrices
- Diagonalize phonon Hamiltonians to extract frequencies and modes
- Compute commensurate supercells for charge density wave (CDW) distortions
- Build distorted atomic configurations based on soft phonon modes

The main abstractions in this module are:

- `Dyn`: Represents a single dynamical matrix at a given q-point. Provides diagonalization and unit conversion.
- `CDW`: Builds a supercell compatible with multiple q-points and applies structural distortions.

Classes
-------
Dyn
    Container for a dynamical matrix at a specific q-point. Provides file I/O, diagonalization,
    and access to phonon frequencies and displacements.
    Provides:
    - from_file(): Class method to construct a `Dyn` object by reading a `.dyn*` file from Quantum ESPRESSO output.
    - diagonalize(): Diagonalizes the dynamical matrix, returning phonon frequencies and eigenvectors.

CDW
    Constructs and manipulates charge-density wave (CDW) distorted supercells from
    multiple q-point phonon modes.
    Provides:
    - from_file(): Class method to initialize a `CDW` object by reading `.dyn*` files at one or more q-points.
    - distort_crystal(): Applies the displacement pattern of selected phonon modes to the supercell.
    - sym_analysis(): Perform a symmetry analysis of commensurate CDW distortions across a grid of order parameters.

Functions
---------
_QEdyn2Realdyn(dyn_mat, masses)
    Convert a QE-format dynamical matrix (with √(mᵢ mⱼ) prefactors) to the true physical matrix
    whose eigenvalues are phonon frequencies squared (in s⁻² or (Ry/h)²).

_find_supercell(q_cryst)
    Given one or more q-points, computes the minimal supercell for which exp(2πi·q·R)
    is periodic over the lattice. Returns supercell size and grid of phase factors.

_format_input(CDW, order_parameter, modes, grid)
    Formats and normalizes user input for a CDW distortion calculation.

Examples
--------
>>> from yaiv.phonon import Dyn
>>> dyn = Dyn.from_file(q_cryst=[0.5, 0.0, 0.0], results_ph_path="ph_output/")
>>> dyn.diagonalize()
>>> dyn.freqs  # phonon frequencies in cm⁻¹

>>> from yaiv.phonon import CDW
>>> cdw = CDW.from_file(q_cryst=[[0,0,0],[1/2, 0.0, 0.0]], results_ph_path="ph_output/")
>>> distorted = cdw.distort_crystal(order_parameter=[1,1/5], modes=[0,0], amplitude=0.05)

See Also
--------
yaiv.grep         : Greps structural and vibrational data from output files
yaiv.cell         : Atomic structure container and symmetry wrapper
yaiv.utils        : Unit management and basis transformation utilities
"""

from types import SimpleNamespace
from math import gcd
import warnings

import numpy as np
import spglib as spg

from yaiv.defaults.config import ureg
from yaiv.defaults.config import defaults
from yaiv import utils as ut
from yaiv import grep
from yaiv import cell
from yaiv.dev import grep as grepx


__all__ = ["Dyn", "CDW"]


def _QEdyn2Realdyn(
    dyn_mat: np.ndarray | ureg.Quantity, masses: np.ndarray | ureg.Quantity
) -> np.ndarray | ureg.Quantity:
    """
    Convert Quantum ESPRESSO dynamical matrix to the real dynamical matrix in physical units.

    In Quantum ESPRESSO, the dynamical matrix is written in units of [energy/h]^2 * [mass].
    To obtain the true dynamical matrix, whose eigenvalues are squared phonon frequencies (ν²) in
    units of [energy/h]^2, one must divide by √(m_i * m_j) for each atomic block.

    Parameters
    ----------
    dyn_mat : np.ndarray | ureg.Quantity
        The 3N×3N dynamical matrix as written by Quantum ESPRESSO.

    masses : np.ndarray | ureg.Quantity
        Array of atomic masses (length N), one per atom. Units should be consistent
        with those implied in `dyn_mat`. In QE, masses are typically given in units of 2 m_e.

    Returns
    -------
    np.ndarray or Quantity
        The real dynamical matrix with proper normalization, whose eigenvalues
        have units of squared frequencies, e.g., [Ry²/h²] or [s⁻²], depending on units.

    Raises
    ------
    ValueError
        If input shapes are inconsistent or mass array is not one-dimensional.
    """
    # Check unit consistency
    ut._check_unit_consistency([dyn_mat, masses], ["Dynamical matrix", "Atomic masses"])

    # Strip units if present
    if isinstance(dyn_mat, ureg.Quantity):
        units = dyn_mat.units / masses.units
        dyn_mat = dyn_mat.magnitude
        masses = masses.magnitude
    else:
        units = 1

    # Sanity checks
    masses = np.asarray(masses)
    dyn_mat = np.asarray(dyn_mat)

    if masses.ndim != 1:
        raise ValueError("Masses must be a 1D array (one mass per atom).")
    if dyn_mat.shape[0] != dyn_mat.shape[1]:
        raise ValueError("Dynamical matrix must be square.")
    if dyn_mat.shape[0] != 3 * len(masses):
        raise ValueError("Dynamical matrix shape is incompatible with number of atoms.")

    # Transform matrix
    N = len(masses)
    dyn = np.copy(dyn_mat)
    for n in range(N):
        for m in range(N):
            i = 3 * n
            j = 3 * m
            factor = np.sqrt(masses[n] * masses[m])
            dyn[i : i + 3, j : j + 3] /= factor

    return dyn * units


class Dyn:
    """
    A container for a single phonon dynamical matrix at a given q-point.

    This class provides functionality to read and manipulate dynamical matrices
    produced by Quantum ESPRESSO, convert them to real physical units, and diagonalize
    them to obtain phonon frequencies and polarization vectors.

    Attributes
    ----------
    q : pint.Quantity [2π/crystal]
        The q-point in reciprocal space (reduced coordinates).
    dyn : np.ndarray or Quantity
        The dynamical matrix, either in QE format (with mass prefactors) or physical units.
    Cell : cell.Cell
        The atomic structure associated with this q-point, including lattice, positions, elements.
    masses : Quantity [2*m_e]
        Array of atomic masses, usually in units of 2 electron masses as per QE convention.
    freqs : Quantity [cm⁻¹], optional
        Frequencies of the phonon modes after diagonalization.
    displacements : np.ndarray, optional
        Mass-normalized eigenvectors (displacements). Shape and units depend on output format.
    polarizations : np.ndarray, optional
        Raw polarization vectors before mass normalization.
    """

    def __init__(
        self,
        q=None,
        dyn=None,
        masses=None,
        Cell=None,
    ):
        """
        dyn_mat : np.ndarray | ureg.Quantity
            The (3N × 3N) complex-valued dynamical matrix. If `qe_format_in=True`, this is expected to
            be the raw QE format (including √(mᵢ mⱼ) prefactors); otherwise, it should already be the
            physical dynamical matrix in (Ry/h)² units.

        masses : np.ndarray | ureg.Quantity
            Atomic masses in units of used in the dynamical matrix if qe_format_in is True.
        """
        self.q = q
        self.dyn = dyn
        self.Cell = Cell
        self.masses = masses

    @classmethod
    def from_file(
        cls,
        q_cryst: np.ndarray | ureg.Quantity,
        results_ph_path: str,
        qe_format: bool = True,
    ):
        """
        Reads the Quantum ESPRESSO `.dyn*` file corresponding to a given q-point.

        This function locates the `.dyn*` file generated by `ph.x` that corresponds to a
        desired q-point (in reduced crystalline coordinates), extracts the corresponding dynamical
        matrix, and optionally converts it to the real physical dynamical matrix in units
        of 1 / [time]².

        Parameters
        ----------
        q_cryst : np.ndarray | ureg.Quantity
            The q-point of interest, expressed in reduced crystalline coordinates (fractions of reciprocal lattice vectors).
            If not a `Quantity`, it is assumed to be in `_2pi/crystal` units.

        results_ph_path : str
            Path to the directory containing the Quantum ESPRESSO `ph.x` output `.dyn*` files.

        qe_format : bool, optional
            If True (default), returns the raw QE dynamical matrix (includes sqrt(m_i m_j) mass factors).
            If False, converts the dynamical matrix to true physical form in 1 / [time]² units (Ry/h)^2.

        Returns
        -------
        Dyn
            A new Dynamical matrix instance.
        """
        system = grepx.dyn_q(q_cryst, results_ph_path, qe_format)
        atoms = cell.Atoms(
            system.elements, system.positions.magnitude, cell=system.lattice.magnitude
        )
        return cls(
            q=system.q,
            dyn=system.dyn,
            Cell=cell.Cell(atoms=atoms),
            masses=system.masses,
        )

    def diagonalize(
        self,
        qe_format_in: bool = True,
        qe_format_out: bool = True,
    ):
        """
        Diagonalize a dynamical matrix and return phonon frequencies, polarization vectors and displacements.

        This function converts the input dynamical matrix to its physical form (if needed),
        diagonalizes it to obtain phonon frequencies (in cm⁻¹), and computes the corresponding
        normalized displacement vectors.

        Parameters
        ----------
        qe_format_in : bool, optional
            Whether `dyn_mat` is in QE format (default: True). If so, it is converted to the real
            physical format for diagonalization.

        qe_format_out : bool, optional
            Whether to return the normalized displacements and polarization vectors in QE format: an array of shape
            (3N, N_atoms, 3). If False, returns a plain (3N × 3N) array of normalized eigenvectors/displacements where
            polarizations[i] corresponds to eigenvalue freqs[i]**2.

        Returns
        -------
        New attributes to the Dyn object:
            - freqs : np.ndarray
                Array of 3N phonon frequencies in cm⁻¹. Real or negative imaginary parts indicate stable or unstable modes.
            - displacements : np.ndarray
                Normalized displacement vectors of the dynamical matrix. Format depends on `qe_format_out`.
            - polarizations : np.ndarray
                Raw polarization vectors (before mass-weighted normalization). Format depends on `qe_format_out`.

        Raises
        ------
        ValueError
            If eigenvalues are not purely real or imaginary (i.e., contain both parts).
        """
        # Check unit consistency
        dyn_mat, masses = self.dyn, self.masses
        ut._check_unit_consistency(
            [dyn_mat, masses], ["Dynamical matrix", "Atomic masses"]
        )

        # Strip units
        if isinstance(dyn_mat, ureg.Quantity):
            if dyn_mat.dimensionality == ureg("kg/s^2").dimensionality:
                dyn_mat = _QEdyn2Realdyn(dyn_mat, masses)
            dyn, units = dyn_mat.magnitude, (1 * np.sqrt(dyn_mat).units).to("c/cm")
            masses = masses.magnitude
        else:
            if qe_format_in:
                dyn_mat = _QEdyn2Realdyn(dyn_mat, masses)
            dyn, units = dyn_mat, 1

        # Diagonalize
        eigvals, pol = np.linalg.eig(dyn)

        # Convert eigenvalues (ω²) to frequencies in cm⁻¹
        freqs = np.zeros_like(eigvals, dtype=float)
        for i, val in enumerate(np.sqrt(eigvals)):
            if np.isclose(np.imag(val), 0, atol=1e-10):
                freqs[i] = np.real(val)
            elif np.isclose(np.real(val), 0, atol=1e-10):
                freqs[i] = -np.abs(np.imag(val))
            else:
                raise ValueError(
                    f"Complex eigenvalue with both real and imaginary part at index {i}: {val}"
                )

        # Normalize polarization vectors to obtain displacements
        dim = len(masses)
        displacements = np.copy(pol)
        for col in range(pol.shape[1]):
            for i in range(dim):
                displacements[3 * i : 3 * i + 3, col] /= np.sqrt(masses[i])
            displacements[:, col] /= np.linalg.norm(displacements[:, col])

        # Sort by increasing frequency
        order = np.argsort(freqs)
        freqs_sorted = freqs[order] * units
        displacements = displacements[:, order].T
        polarizations = pol[:, order].T

        if qe_format_out:
            displacements = displacements.reshape(len(masses) * 3, len(masses), 3)
            polarizations = polarizations.reshape(len(masses) * 3, len(masses), 3)

        self.freqs = freqs_sorted
        self.displacements = displacements
        self.polarizations = polarizations


def _find_supercell(
    q_cryst: np.ndarray | ureg.Quantity | list[np.ndarray] | list[ureg.Quantity],
) -> SimpleNamespace:
    """
    Compute the minimal supercell that is commensurate with a set of q-points in crystal units.

    This function finds the smallest supercell that accommodates the periodicity
    of the input q-points by ensuring that the phase factors `exp(2πi q·R)` close
    after a finite number of lattice translations. It also computes the corresponding
    phase factor grids over the supercell.

    Parameters
    ----------
    q_cryst : np.ndarray | ureg.Quantity | list[np.ndarray | ureg.Quantity]
        A single q-point or list of q-points, given in crystalline units
        (units of 2π/crystal). If provided with units, they must be `"_2pi/crystal"`.

    Returns
    -------
    SimpleNamespace
        A namespace with the following attributes:
        - size : np.ndarray
            A 3-element integer array defining the minimal commensurate supercell.
        - phase_factors : list[np.ndarray]
            List of 3D complex-valued arrays with the phase factors
            `exp(2πi q·R)` evaluated on the supercell grid for each q-point.
            Each has dimnesion equal to the supercell size [phase_factors.shape = size].
        - q : list[ureg.Quantity]
            The q-points, returned as quantities with units `_2pi/crystal`.

    Raises
    ------
    ValueError
        If q-points do not have units of 2π/crystal, or if no commensurate supercell
        is found in a direction within 100 lattice multiples.
    """
    # Normalize input to list of np.ndarray
    if len(np.shape(q_cryst)) == 1:
        q_cryst = [q_cryst]

    # Check units and convert to magnitudes
    ut._check_unit_consistency(q_cryst)
    if isinstance(q_cryst[0], ureg.Quantity):
        for q in q_cryst:
            if q.units != ureg("_2pi/crystal"):
                raise ValueError("Each q-point must have units of 2π/crystal.")
        q_cryst_mag = [q.magnitude for q in q_cryst]
    else:
        q_cryst_mag = q_cryst

    supersize = np.ones(3, dtype=int)

    for q in q_cryst_mag:
        p_super = np.zeros(3, dtype=int)
        for i, n in enumerate(q):
            for cell in range(1, 101):
                if (cell * n) % 1 == 0:
                    p_super[i] = cell
                    break
            else:
                raise ValueError(
                    f"Could not find commensurate cell for q = {q} in direction {i} "
                    "within 100 multiples. Check that q is rational."
                )
        # LCM between existing and partial supercell
        for i in range(3):
            supersize[i] = supersize[i] * p_super[i] // gcd(supersize[i], p_super[i])

    # Compute phase factors over supercell grid
    phase_factors = []
    for q in q_cryst_mag:
        phases_q = np.empty(supersize, dtype=complex)
        for i in range(supersize[0]):
            for j in range(supersize[1]):
                for k in range(supersize[2]):
                    R = np.array([i, j, k])
                    phases_q[i, j, k] = np.exp(2j * np.pi * np.dot(q, R))
        phase_factors.append(phases_q)

    q_cryst_with_units = [np.array(q) * ureg("_2pi/crystal") for q in q_cryst_mag]

    return SimpleNamespace(
        size=supersize,
        phase_factors=phase_factors,
        q=q_cryst_with_units,
    )


class CDW:
    """
    Class representing a charge-density wave (CDW) structure built from a set
    of phonon dynamical matrices at different q-points.

    This class:
    - Stores the dynamical matrices.
    - Determines the commensurate supercell that accommodates the q-points.
    - Builds the corresponding supercell.
    - Applies distortions associated with the soft phonon modes.

    Attributes
    ----------
    dyn_matrices : list
        List of `Dyn` objects, each containing a dynamical matrix and metadata.
    Cell : Cell
        The primitive unit cell object, taken from the first `Dyn` entry.
    q : list[np.ndarray]
        List of q-points (in 2π/crystal units) corresponding to the dynamical matrices.
    _supercell : SimpleNamespace
        Contains the commensurate supercell size and phase factors.
    SuperCell : Cell
        The supercell constructed from the primitive cell and commensurate size.
    """

    def __init__(self, dyn_matrices: list):
        """
        Initialize the CDW object from a list of `Dyn` objects.

        Parameters
        ----------
        dyn_matrices : list of Dyn
            List of dynamical matrices at different q-points.

        Raises
        ------
        ValueError
            If q-points do not have units of 2π/crystal.
        """
        self.dyn_matrices = dyn_matrices
        self.Cell = self.dyn_matrices[0].Cell

        # Diagonalize and extract q-points
        q_cryst = []
        for dyn in self.dyn_matrices:
            dyn.diagonalize()
            q_cryst.append(dyn.q)
        ut._check_unit_consistency(q_cryst)
        if isinstance(q_cryst[0], ureg.Quantity):
            for q in q_cryst:
                if q.units != ureg("_2pi/crystal"):
                    raise ValueError("Each q-point must have units of 2π/crystal.")
            q_cryst_mag = [q.magnitude for q in q_cryst]
        else:
            q_cryst_mag = q_cryst
        self.q = q_cryst_mag * ureg("_2pi/crystal")

        # Determine supercell and construct it
        self._supercell = _find_supercell(self.q)
        self.SuperCell = self.Cell.get_supercell(self._supercell.size)

    @classmethod
    def from_file(cls, q_cryst, results_ph_path):
        """
        Construct a CDW object by reading .dyn files from a directory.

        Parameters
        ----------
        q_cryst : np.ndarray or list[np.ndarray]
            One or more q-points to read (in 2π/crystal units).
        results_ph_path : str
            Path to folder containing QE phonon outputs (.dyn*).

        Returns
        -------
        CDW
            The constructed CDW object.
        """
        if len(np.shape(q_cryst)) == 1:
            q_cryst = [q_cryst]
        dyn_matrices = [Dyn.from_file(q, results_ph_path) for q in q_cryst]
        return cls(dyn_matrices)

    def distort_crystal(
        self,
        order_parameter: list[complex] = None,
        modes: list[int] = None,
        amplitude: complex = 0.01,
    ):
        """
        Apply a charge density wave distortion to the supercell.

        Parameters
        ----------
        order_parameter : list[complex], optional
            List of complex amplitudes (including phase) for each q-mode. Default being
            a value of 1 for each q-point (np.ones(len(self.q))).
        modes : list[int], optional
            List of mode indices to be activated at each q-point. Default being the
            lowest energy mode for each q point.
        amplitude : complex, optional
            Global scaling factor applied to each distortion vector. Final displacement is given by:
            `Real( Σ (OP * amplitude * displacement))` in Å.

        Returns
        -------
        Cell
            A new `Cell` object representing the distorted supercell.
        """
        _formatted = _format_input(self, order_parameter=order_parameter, modes=modes)
        order_parameter, modes = _formatted.order_parameter, _formatted.modes

        supercell_ind = 0
        cell_size = len(self.Cell[1])
        # Positions are given in angstroms
        positions = np.copy(self.SuperCell.atoms.positions)
        OP = np.array(order_parameter) * amplitude

        for i in range(self._supercell.size[0]):
            for j in range(self._supercell.size[1]):
                for k in range(self._supercell.size[2]):
                    for q_ind in range(len(self.q)):
                        start = supercell_ind * cell_size
                        end = (supercell_ind + 1) * cell_size
                        phase = self._supercell.phase_factors[q_ind][i, j, k]
                        displacements = self.dyn_matrices[q_ind].displacements[
                            modes[q_ind]
                        ]
                        positions[start:end] += np.real(
                            displacements * phase * OP[q_ind]
                        )
                    supercell_ind += 1
        # Construct new Atoms object and return as Cell
        distorted = cell.Atoms(
            self.SuperCell.atoms.numbers, positions, cell=self.SuperCell.atoms.cell
        )
        return cell.Cell(atoms=distorted)

    def sym_analysis(
        self,
        modes: list[int] = None,
        grid: list[int] = None,
        amplitude: complex | list[complex] = 0.01,
        symprec: float = defaults.symprec,
    ):
        """
        Perform a symmetry analysis of commensurate CDW distortions across a grid of order parameters.

        This function generates all symmetry-inequivalent distortions resulting from a combination
        of phonon modes and computes the resulting space groups after displacing atoms along the
        corresponding eigenvectors with various amplitudes.

        Parameters
        ----------
        modes : list[int], optional
            List of mode indices (starting at 0) to be used for the displacement. If None, the lowest
            frequency modes will be selected.

        grid : list[int], optional Grid resolution for scanning order parameters in each mode direction. Each entry N_i sets
            the number of points in [-1, 1] for the i-th mode. Defaults to [3, 3, ..., 3].

        amplitude : complex | list[complex], optional
            Scaling factor applied to each distortion vector. Final displacement is given by:
            `Real( Σ (OP * amplitude * displacement))` in Å.

        symprec : float, optional
            Tolerance used by spglib to determine space group symmetry. Default is `defaults.symprec`.

        Returns
        -------
        SimpleNamespace
            Contains:
            - order_parameters : np.ndarray
                Array of real-valued vectors defining the grid of order parameter values.
            - space_groups : list[str]
                List of space group symbols (e.g. 'P1', 'R-3m') returned by spglib.
            - cell_sizes : np.ndarray
                Ratio of the number of atoms in the distorted supercell to the original cell.
            - structures : list[cell.Cell]
                List of distorted crystal structures.
            - amplitudes : list[complex]
                List of amplitudes (global factor) for each mode.

        Notes
        -----
        - For even-sized grids, the origin (0) will not be included.
        - This function relies on `spglib` to determine space groups and primitive cells.
        """

        _formatted = _format_input(self, grid=grid, modes=modes, amplitude=amplitude)
        grid, modes, amplitude = _formatted.grid, _formatted.modes, _formatted.amplitude

        # Generate order parameters and distort
        OPs = ut.grid_generator(grid)
        num_in_atoms = len(self.Cell[1])
        SGs, sizes, structures = [], [], []

        for OP in OPs:
            distorted = self.distort_crystal(
                order_parameter=OP * amplitude, modes=modes, amplitude=1
            )
            SG = spg.get_spacegroup(distorted, symprec=symprec)
            num_out_atoms = len(spg.find_primitive(distorted, symprec=symprec)[1])
            s = int(num_out_atoms / num_in_atoms)
            SGs.append(SG)
            sizes.append(s)
            structures.append(distorted)

        return SimpleNamespace(
            order_parameters=OPs,
            space_groups=SGs,
            cell_sizes=np.array(sizes),
            structures=structures,
            amplitudes=amplitude,
        )


def _format_input(
    CDW: CDW,
    order_parameter: list[complex] = None,
    modes: list[int] = None,
    grid: list[int] = None,
    amplitude: complex | list[complex] = None,
):
    """
    Formats and normalizes user input for a CDW distortion calculation.

    Ensures that `order_parameter`, `modes`, and `grid` are provided in consistent list formats.
    Defaults are assigned based on the number of q-vectors in the CDW object.

    Parameters
    ----------
    CDW : CDW
        CDW object containing the q-vectors and structure information.
    order_parameter : list[complex] or scalar, optional
        Complex order parameter for each mode. Defaults to `[1, ..., 1]` (real).
        If a scalar is given, it is broadcasted.
    modes : list[int] or int, optional
        List of phonon mode indices corresponding to each q-vector. Defaults to lowest-frequency modes (0).
        If a single integer is given, it is wrapped in a list.
    grid : list[int] or int, optional
        Number of points per direction in the grid of order parameters. Defaults to `[3, ..., 3]`.
        If a scalar is given, it is broadcasted.
    amplitude : list[complex] or complex, optional
        Complex amplitudes for each mode. Defaults to 0.01 (real).

    Returns
    -------
    SimpleNamespace
        A namespace with normalized fields:
        - order_parameter : list[complex]
        - modes : list[int]
        - grid : list[int]
        - amplitude : list[complex]
    """
    DIM = len(CDW.q)

    # Order parameter
    if order_parameter is None:
        order_parameter = np.ones(DIM, dtype=complex)
    elif isinstance(order_parameter, (complex, float, int)):
        order_parameter = [order_parameter]

    # Modes
    if modes is None:
        modes = np.zeros(DIM, dtype=int)
    elif isinstance(modes, int):
        modes = [modes]

    # Grid
    if grid is None:
        grid = np.ones(DIM, dtype=int) * 3
    elif isinstance(grid, int):
        grid = [grid]

    # Amplitude
    if isinstance(amplitude, (complex, float, int)):
        amplitude = np.array([amplitude] * DIM)

    return SimpleNamespace(
        order_parameter=order_parameter, modes=modes, grid=grid, amplitude=amplitude
    )


class BOES:
    def __init__(self, CDW: CDW = None):
        self.CDW = CDW

    def generate_structures_grid(
        self,
        grid: list[int] = None,
        modes: list[int] = None,
        amplitude: complex | list[complex] = 0.01,
    ):

        _formatted = _format_input(
            self.CDW, grid=grid, modes=modes, amplitude=amplitude
        )
        grid, modes, amplitude = _formatted.grid, _formatted.modes, _formatted.amplitude

        print("---------------------------------------------------")
        print(
            "Order parameter in a",
            grid,
            "grid  // ",
            "Amplitudes = ",
            amplitude,
        )
        print()
        print("The general displacement at each config is given by:")
        print("Real ( Σ (OP * amplitudes * displacements)) * Å")
        print()
        print("---------------------------------------------------")
        print(
            'Final applied "maximum" displacement (Å): (Σ abs(amplitudes) * displacements ) ='
        )
        distorted = self.CDW.distort_crystal(
            order_parameter=np.abs(amplitude), modes=modes, amplitude=1
        )
        displacement = (
            self.CDW.Cell.atoms.positions
            - distorted.atoms.positions[: len(self.CDW.Cell[1])]
        )
        print(np.around(displacement, decimals=5))

        out = self.CDW.sym_analysis(modes=modes, grid=grid, amplitude=amplitude)
        self.structures = out.structures
        self.order_parameters = out.order_parameters
        self.amplitudes = out.amplitudes

    def saveas_jobs_pwi(
        self,
        dest_folder: str = None,
        template: str = None,
        primitive: bool = False,
        symprec: float = defaults.symprec,
        write: bool = False,
    ):
        """Creates the necessary QE inputs to create an energy landscape for any combination of order parameters.
        All the information of the created configurations will be saved into a "surf.txt" file.
        There are two main modes:
            GRIDMODE : It creates an uniform grid in the Order parameter space.
            LINEMODE : It explores a predefined direction in the Order parameter space.

        q_cryst = q points you are interested in crystaline units.
        results_ph_path = Folder where you ph.x output is stored.
        dest_folder = Folder where your inputs will be stored.
        template = A template QE input you want to copy to generate your inputs.
        OP = If OP is defined, then LINEMODE is activated and OP defines your direction in the Order Parameter space.
        grid = In GRIDMODE:
                [N1,N2,N3...] describing your grid (between [-1,1])
                By default will be a [2,2,2...] grid
                If Ni=1 then Xi=1 for all points
               In LINEMODE:
                It defines the number of points in your line.
        freq = index of the frequenzies you are interested in (starting at 1).
                By default it will take the lowest frequency ones.
        boundary = In GRIDMODE:
                   Amount of distortion in any the desired direction.
                   It also supports a LIST input so you define a different value for each grid component.
                   The final distortion will be multiplied by this factor.
                   In LINEMODE:
                   The boundary factors by which you want to multiply your order parameter (OP).
        primitive = (Boolean) Whether you want to resulting structures in primitive cell or in supercell form.
        symprec = Symmetry thushold as defined by spglib.
        write = (Bolean) Whether to write the results in your filesystem. Defaulted to False in order to avoid overwritting a previous configuration.
        """

    def _plot_energy_landscape(self):
        pass

    def _read_energy_surf_data_txt(file):
        pass
j
    def _read_energy_surf_data(self):
        pass
