from types import SimpleNamespace

import numpy as np

from yaiv.defaults.config import ureg
from yaiv import utils as ut
from yaiv import grep
from yaiv import cell
from yaiv.dev import grep as grepx


__all__ = ["Dyn", "CDW"]


def _QEdyn2Realdyn(
    dyn_mat: np.ndarray | ureg.Quantity, masses: np.ndarray | ureg.Quantity
) -> np.ndarray | ureg.Quantity:
    """
    Convert Quantum ESPRESSO dynamical matrix to the real dynamical matrix in physical units.

    In Quantum ESPRESSO, the dynamical matrix is written in units of [energy/h]^2 * [mass].
    To obtain the true dynamical matrix, whose eigenvalues are squared phonon frequencies (ν²) in
    units of [energy/h]^2, one must divide by √(m_i * m_j) for each atomic block.

    Parameters
    ----------
    dyn_mat : np.ndarray | ureg.Quantity
        The 3N×3N dynamical matrix as written by Quantum ESPRESSO.

    masses : np.ndarray | ureg.Quantity
        Array of atomic masses (length N), one per atom. Units should be consistent
        with those implied in `dyn_mat`. In QE, masses are typically given in units of 2 m_e.

    Returns
    -------
    np.ndarray or Quantity
        The real dynamical matrix with proper normalization, whose eigenvalues
        have units of squared frequencies, e.g., [Ry²/h²] or [s⁻²], depending on units.

    Raises
    ------
    ValueError
        If input shapes are inconsistent or mass array is not one-dimensional.
    """
    # Check unit consistency
    ut._check_unit_consistency([dyn_mat, masses], ["Dynamical matrix", "Atomic masses"])

    # Strip units if present
    if isinstance(dyn_mat, ureg.Quantity):
        units = dyn_mat.units / masses.units
        dyn_mat = dyn_mat.magnitude
        masses = masses.magnitude
    else:
        units = 1

    # Sanity checks
    masses = np.asarray(masses)
    dyn_mat = np.asarray(dyn_mat)

    if masses.ndim != 1:
        raise ValueError("Masses must be a 1D array (one mass per atom).")
    if dyn_mat.shape[0] != dyn_mat.shape[1]:
        raise ValueError("Dynamical matrix must be square.")
    if dyn_mat.shape[0] != 3 * len(masses):
        raise ValueError("Dynamical matrix shape is incompatible with number of atoms.")

    # Transform matrix
    N = len(masses)
    dyn = np.copy(dyn_mat)
    for n in range(N):
        for m in range(N):
            i = 3 * n
            j = 3 * m
            factor = np.sqrt(masses[n] * masses[m])
            dyn[i : i + 3, j : j + 3] /= factor

    return dyn * units


class Dyn:
    def __init__(
        self,
        q=None,
        dyn=None,
        masses=None,
        Cell=None,
    ):
        """
        dyn_mat : np.ndarray | ureg.Quantity
            The (3N × 3N) complex-valued dynamical matrix. If `qe_format_in=True`, this is expected to
            be the raw QE format (including √(mᵢ mⱼ) prefactors); otherwise, it should already be the
            physical dynamical matrix in (Ry/h)² units.

        masses : np.ndarray | ureg.Quantity
            Atomic masses in units of used in the dynamical matrix if qe_format_in is True.
        """
        self.q = q
        self.dyn = dyn
        self.Cell = Cell
        self.masses = masses

    @classmethod
    def from_file(
        cls,
        q_cryst: np.ndarray | ureg.Quantity,
        results_ph_path: str,
        qe_format: bool = True,
    ):
        """
        Reads the Quantum ESPRESSO `.dyn*` file corresponding to a given q-point.

        This function locates the `.dyn*` file generated by `ph.x` that corresponds to a
        desired q-point (in reduced crystalline coordinates), extracts the corresponding dynamical
        matrix, and optionally converts it to the real physical dynamical matrix in units
        of 1 / [time]².

        Parameters
        ----------
        q_cryst : np.ndarray | ureg.Quantity
            The q-point of interest, expressed in reduced crystalline coordinates (fractions of reciprocal lattice vectors).
            If not a `Quantity`, it is assumed to be in `_2pi/crystal` units.

        results_ph_path : str
            Path to the directory containing the Quantum ESPRESSO `ph.x` output `.dyn*` files.

        qe_format : bool, optional
            If True (default), returns the raw QE dynamical matrix (includes sqrt(m_i m_j) mass factors).
            If False, converts the dynamical matrix to true physical form in 1 / [time]² units (Ry/h)^2.

        Returns
        -------
        Dyn
            A new Dynamical matrix instance.
        """
        system = grepx.read_dyn_q(q_cryst, results_ph_path, qe_format)
        atoms = cell.Atoms(
            system.elements, system.positions.magnitude, cell=system.lattice.magnitude
        )
        return cls(
            q=system.q,
            dyn=system.dyn,
            Cell=cell.Cell(atoms=atoms),
            masses=system.masses,
        )

    def diagonalize(
        self,
        qe_format_in: bool = True,
        qe_format_out: bool = True,
    ):
        """
        Diagonalize a dynamical matrix and return phonon frequencies, polarization vectors and displacements.

        This function converts the input dynamical matrix to its physical form (if needed),
        diagonalizes it to obtain phonon frequencies (in cm⁻¹), and computes the corresponding
        normalized displacement vectors.

        Parameters
        ----------
        qe_format_in : bool, optional
            Whether `dyn_mat` is in QE format (default: True). If so, it is converted to the real
            physical format for diagonalization.

        qe_format_out : bool, optional
            Whether to return the normalized displacements and polarization vectors in QE format: an array of shape
            (3N, N_atoms, 3). If False, returns a plain (3N × 3N) array of normalized eigenvectors/displacements where
            polarizations[i] corresponds to eigenvalue freqs[i]**2.

        Returns
        -------
        New attributes to the Dyn object:
            - freqs : np.ndarray
                Array of 3N phonon frequencies in cm⁻¹. Real or negative imaginary parts indicate stable or unstable modes.
            - displacements : np.ndarray
                Normalized displacement vectors of the dynamical matrix. Format depends on `qe_format_out`.
            - polarizations : np.ndarray
                Raw polarization vectors (before mass-weighted normalization). Format depends on `qe_format_out`.

        Raises
        ------
        ValueError
            If eigenvalues are not purely real or imaginary (i.e., contain both parts).
        """
        # Check unit consistency
        dyn_mat, masses = self.dyn, self.masses
        ut._check_unit_consistency(
            [dyn_mat, masses], ["Dynamical matrix", "Atomic masses"]
        )

        # Strip units
        if isinstance(dyn_mat, ureg.Quantity):
            if dyn_mat.dimensionality == ureg("kg/s^2").dimensionality:
                dyn_mat = _QEdyn2Realdyn(dyn_mat, masses)
            dyn, units = dyn_mat.magnitude, (1 * np.sqrt(dyn_mat).units).to("c/cm")
            masses = masses.magnitude
        else:
            if qe_format_in:
                dyn_mat = _QEdyn2Realdyn(dyn_mat, masses)
            dyn, units = dyn_mat, 1

        # Diagonalize
        eigvals, pol = np.linalg.eig(dyn)

        # Convert eigenvalues (ω²) to frequencies in cm⁻¹
        freqs = np.zeros_like(eigvals, dtype=float)
        for i, val in enumerate(np.sqrt(eigvals)):
            if np.isclose(np.imag(val), 0, atol=1e-10):
                freqs[i] = np.real(val)
            elif np.isclose(np.real(val), 0, atol=1e-10):
                freqs[i] = -np.abs(np.imag(val))
            else:
                raise ValueError(
                    f"Complex eigenvalue with both real and imaginary part at index {i}: {val}"
                )

        # Normalize polarization vectors to obtain displacements
        dim = len(masses)
        displacements = np.copy(pol)
        for col in range(pol.shape[1]):
            for i in range(dim):
                displacements[3 * i : 3 * i + 3, col] /= np.sqrt(masses[i])
            displacements[:, col] /= np.linalg.norm(displacements[:, col])

        # Sort by increasing frequency
        order = np.argsort(freqs)
        freqs_sorted = freqs[order] * units
        displacements = displacements[:, order].T
        polarizations = pol[:, order].T

        if qe_format_out:
            displacements = displacements.reshape(len(masses) * 3, len(masses), 3)
            polarizations = polarizations.reshape(len(masses) * 3, len(masses), 3)

        self.freqs = freqs_sorted
        self.displacements = displacements
        self.polarizations = polarizations


# def distort_crystal(q_points, results_ph, order_parameter, modes, amplitude):
class CDW:
    def __init__(self, q_cryst, results_ph_path):
        if len(np.shape(q_cryst)) == 1:
            q_cryst = [q_cryst]
        print("TODO")
        DYNS = []
        for q in q_cryst:
            DYNS = DYNS + [Dyn.from_file(q, results_ph_path)]
        self.DYNS=DYNS
        # 1. Read crystal structure
        # 2. Get dynamical matrices
        # 3. Diagonalize matrices
        # 4. Get displacement vectors
        # 5. Find conmmensurate supercell
        # 6. Get proper phase factors for each cell
        pass

    def distort_crystal(order_parameter, modes, amplitude):
        print("TODO")
        # 7. Make Supercell displacement vectors combining phase factors and displacement vectors
        # 8. Add the displacements to create a supercell final displacement
        # 9. Apply displacement
        # 10. Return final cell
        pass
